server:
  port: 8082

spring:
  application:
    name: truck-service
  datasource:
    url: jdbc:mysql://localhost:3306/cargoflow_truck_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  sql:
    init:
      mode: never

logging:
  level:
    com.cargoflow.truckservice: DEBUG
    org.springframework.web: DEBUG
